In [11]:
import os
import random
import math

import numpy as np
import pandas as pd
import haven.db as db 
import plotly.express as px

from mirrorverse.utils import read_data_w_cache

os.environ['HAVEN_DATABASE'] = 'haven'
os.environ['AWS_PROFILE'] = 'admin'

In [2]:
sql = '''
select 
    *
from 
    movement_model_contrasts_m3_a3
'''
data = read_data_w_cache(sql)

In [9]:
decisions_to_keep = data[data['_selected'] & (data['distance'] > 0)][['_individual', '_decision']].drop_duplicates()
to_write = data.merge(decisions_to_keep)
to_write.head()

,_choice,_decision,_old_decision,_old_choice,_selected,mixed_layer_thickness,net_primary_production,water_heading,movement_heading,distance,...,home_lon,normed_home_lat,normed_home_lon,fork_length_cm,normalized_fork_length,cos_time,sin_time,tag_key,_train,partition
0,0,0,1,2,True,27.848141,1.046455,0.782074,1.419472,42.459782,...,360.0,4.0,2.0,85.0,1.344533,1.0,-2.449294e-16,129843,False,0
1,1,1,1,2,True,27.848141,1.046455,0.782074,1.419472,42.459782,...,360.0,4.0,2.0,85.0,1.344533,1.0,-2.449294e-16,129843,False,0
2,2,2,1,2,True,27.848141,1.046455,0.782074,1.419472,42.459782,...,360.0,4.0,2.0,85.0,1.344533,1.0,-2.449294e-16,129843,False,0
3,7,7,1,2,True,27.848141,1.046455,0.782074,1.419472,42.459782,...,360.0,4.0,2.0,85.0,1.344533,1.0,-2.449294e-16,129843,False,0
4,8,8,1,2,True,27.848141,1.046455,0.782074,1.419472,42.459782,...,360.0,4.0,2.0,85.0,1.344533,1.0,-2.449294e-16,129843,False,0

In [10]:
db.write_data(
    to_write, 'movement_model_contrasts_m4_a1', ['partition']
)

In [16]:
sql = '''
select 
    *
from 
    movement_model_features_m3_a2_test
'''
data = read_data_w_cache(sql)

In [17]:
decisions_to_keep = data[data['_selected'] & (data['distance'] > 0)][['_individual', '_decision']].drop_duplicates()
to_write = data.merge(decisions_to_keep)
to_write.head()

,_decision,_choice,_selected,mixed_layer_thickness,net_primary_production,water_heading,movement_heading,distance,origin_h3_index,next_h3_index,...,region,home_lat,home_lon,normed_home_lat,normed_home_lon,fork_length_cm,normalized_fork_length,cos_time,sin_time,tag_key
0,21,2,False,17.192094,10.707186,-1.164854,-0.379848,91.876343,8422cc1ffffffff,8422cc5ffffffff,...,<NA>,360.0,360.0,4.0,2.0,66.0,-1.350667,-0.654861,-0.75575,142191
1,21,17,False,15.545945,8.184820,0.068610,-0.832805,78.767639,8422cc1ffffffff,8422cc5ffffffff,...,<NA>,360.0,360.0,4.0,2.0,66.0,-1.350667,-0.654861,-0.75575,142191
2,12,1,False,10.533246,7.994629,-2.221257,-2.853354,87.226852,8422cddffffffff,8422cc3ffffffff,...,<NA>,360.0,360.0,4.0,2.0,66.0,-1.350667,-0.654861,-0.75575,142191
3,12,18,False,10.769335,7.983797,2.046756,-0.814624,78.906609,8422cddffffffff,8422cc3ffffffff,...,<NA>,360.0,360.0,4.0,2.0,66.0,-1.350667,-0.654861,-0.75575,142191
4,21,8,False,17.332719,6.059353,0.563373,1.546711,43.574856,8422cc1ffffffff,8422cc5ffffffff,...,<NA>,360.0,360.0,4.0,2.0,66.0,-1.350667,-0.654861,-0.75575,142191

In [18]:
db.write_data(
    to_write, 'movement_model_features_m4_a1_test', ['tag_key']
)